# Generated by Django 5.2 on 2025-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_student_courses_alter_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(blank=True, to="registration.course"),
        ),
    ]
