# Generated by Django 5.2 on 2025-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
